### ISSUE TITLE
无法连接...

### ISSUE THREAD

**Issue by JC-ProPlus** [uupers/save-tieba#5]
并没有看懂这一段错误是怎么回事，就暂且贴在下面吧：
```
(node:4833) UnhandledPromiseRejectionWarning: RequestError: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443
    at new RequestError (/Users/jack/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/jack/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/jack/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/jack/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.onRequestError (/Users/jack/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:197:13)
    at ClientRequest.onError (/Users/jack/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:285:13)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:4833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
```
我写了这样一段Typescript：
```
import { writeFileSync } from 'fs'
import { parserPage } from '@vutex/wapp2md'

let pageID = [5554756235,5874583858,4978194456,5553870498,5876914060,5370501167,5070482430,5109818522,5020614879,5040515255,4895254339,4837826905,4849113851,4778342730,4998358394,5226569599,5394048838,5624632942,5565871259,5459714182,5304062172,5299807814,5261215654,5052908089,5197847676,5154437617,5185964834,5213030256,4946665487,4878018562]
for (var id = 0; id < pageID.length; id++)
{
    parserPage(pageID[id]).then($ => { writeFileSync(`./id.md`, $) })
}
```
然后编译并用node执行了编译后的JavaScript，然后就报了上面的错...
求大佬请教，感激不尽🤔

**Comment by JC-ProPlus** [comment]
已解决...关掉终端代理就好了（
